trigger:
  - main  # Runs pipeline on push to 'main' branch

pool: Newpool1

steps:

  - script: |
      python -m venv venv
      venv\Scripts\activate
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      make test
    displayName: 'Run Tests'