trigger:
  - main  # Runs pipeline on push to 'main' branch

pool: Newpool1

steps:

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    displayName: 'Install Chocolatey'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $env:Path += ";C:\ProgramData\Chocolatey\bin"
        choco install make -y
    displayName: 'Install Make'



  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Use latest Python 3 version
      addToPath: true

  - script: |
      python -m venv venv
      venv\Scripts\activate
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      set PATH=C:\ProgramData\chocolatey\bin;%PATH%
      make test
    displayName: 'Run Tests'