# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: my-pc

steps:
  - script: |
     "C:\Users/hzain/AppData/Local/Programs/Python/Python313/python.exe" --version
    displayName: 'Check Python Version'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      make format-check
    displayName: 'Check code formatting'

  - script: |
      make lint
    displayName: 'Run linting'

  - script: |
      make test
    displayName: 'Run tests with coverage'
