trigger:
  - main  # Runs pipeline on push to 'main' branch

pool: Newpool1

steps:

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $pythonPath = "C:\Users\hzain\AppData\Local\Programs\Python\Python313"  # Update this path based on your installed Python version
        $env:Path += ";$pythonPath;$pythonPath\Scripts"
        Write-Host "##vso[task.setvariable variable=PythonRoot;]$pythonPath"
        Write-Host "Using Python from: $pythonPath"
    displayName: 'Set Up Python'


  - script: |
      python -m venv venv
      venv\Scripts\activate
      pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      make test
    displayName: 'Run Tests'