trigger:
  branches:
    include:
      - main  # Runs CI on the main branch
      - dev   # Runs CI on the dev branch

pool:
  vmImage: 'Default'  # Use your self-hosted agent pool name

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      make format
    displayName: 'Check code formatting'

  - script: |
      make lint
    displayName: 'Run linting'

  - script: |
      make test
    displayName: 'Run tests with coverage'

  - script: |
      pytest --cov=train --cov-report=xml
    displayName: 'Generate coverage report'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'coverage.xml'
    displayName: 'Publish coverage report'
