options:
  logging: CLOUD_LOGGING_ONLY

steps:
# - name: 'gcr.io/cloud-builders/git'
#   args: ['clone', 'https://github.com/Zain-Haider-ML/expert-guacamole.git']

- name: 'python'
  entrypoint: 'python'
  args: ['-m', 'pip', 'install', '--upgrade', 'pip']

- name: 'installing requirements'
  entrypoint: 'python'
  args: ['-m', 'pip', 'install', '-r', 'requirements.txt']

- name: 'python'
  entrypoint: 'make'
  args: ['make', 'install']

- name: 'python'
  entrypoint: 'python'
  args: ['make', 'lint']

- name: 'python'
  entrypoint: 'python'
  args: ['make', 'format']

- name: 'python'
  entrypoint: 'python'
  args: ['make', 'test']