options:
  logging: CLOUD_LOGGING_ONLY

steps:
# - name: 'gcr.io/cloud-builders/git'
#   args: ['clone', 'https://github.com/Zain-Haider-ML/expert-guacamole.git']

- name: 'python'
  entrypoint: 'python'
  args: ['-m', 'pip', 'install', '--upgrade', 'pip']

- name: 'python'
  entrypoint: 'python'
  args: ['-m', 'pip', 'install', '-r', 'requirements.txt']

- name: 'python'
  entrypoint: 'bash'
  args: ['-c', 'apt-get update && apt-get install -y make']

# - name: 'python'
#   entrypoint: 'make'
#   args: ['install']

- name: 'python'
  entrypoint: 'make'
  args: ['lint']

- name: 'python'
  entrypoint: 'make'
  args: ['format']

- name: 'python'
  entrypoint: 'make'
  args: ['test']