options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'python:3.13-slim'
  args: ['clone', 'https://github.com/Zain-Haider-ML/expert-guacamole.git']

- name: 'python:3.13-slim'
  args: ['-m', 'pip', 'install', '-r', 'requirements.txt']

- name: 'python:3.13-slim'
  args: ['make', 'install']

- name: 'python:3.13-slim'
  args: ['make', 'lint']

- name: 'python:3.13-slim'
  args: ['make', 'format']

- name: 'python:3.13-slim'
  args: ['make', 'test']
