name: Wine Recognition

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.13.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.13.2

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        make install

    # Step 4: Lint the code
    - name: Lint
      run: |
        make lint

    # Step 5: Format files
    - name: Format files
      run: |
        make format

    # Step 6: Run tests
    - name: Test
      run: |
        make test

    # Step 7: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 8: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/wine-recognition:${{ github.sha }} .

    # Step 9: Push Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/wine-recognition:${{ github.sha }}
