name: Wine Recognition

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.13.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.13.2

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        make install

    # Step 4: Lint the code
    - name: Lint
      run: |
        make lint

    # Step 5: Format files
    - name: Format files
      run: |
        make format

    # Step 6: Run tests
    - name: Test
      run: |
        make test

    # Step 7: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    # Step 8: Convert repository owner to lowercase
    - name: Convert repository owner to lowercase
      id: lowercase
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    # Step 9: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ env.REPO_OWNER }}/wine-recognition:${{ github.sha }} .

    # Step 10: Push Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ env.REPO_OWNER }}/wine-recognition:${{ github.sha }}
    
  test:
    runs-on: ubuntu-latest
    needs: build  # Ensures the test job runs after the build job completes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 2: Convert repository owner to lowercase (Needed for GHCR)
      - name: Convert repository owner to lowercase
        id: lowercase
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Step 3: Pull the previously built Docker image
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ env.REPO_OWNER }}/wine-recognition:${{ github.sha }}

      # Step 4: Run the Docker container
      - name: Run API Container in Background
        run: |
          docker run -d -p 5000:5000 --name wine-api ghcr.io/${{ env.REPO_OWNER }}/wine-recognition:${{ github.sha }}

      # Step 5: Wait for API to be ready before running Locust
      - name: Wait for API to Start
        run: sleep 5  # Ensures Flask API has time to start before running tests

      # Step 6: Run Load Test using Locust
      - name: Run Load Test
        run: |
          docker exec wine-api locust -f locustfile.py --headless -u 10 -r 2 --run-time 1m --host http://127.0.0.1:5000

      # Step 7: Stop & Remove the Container After Test
      - name: Cleanup Docker Container
        run: |
          if [ "$(docker ps -q -f name=wine-api)" ]; then
            docker stop wine-api
            docker rm wine-api
          fi
